<a href="https://colab.research.google.com/github/brunofbpaula/DataScience-UM-Coursera/blob/main/Numpy/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
It's the fundamental package for numeric computing with Python. It provides powerful ways to create, store, and/or manipulate data, which makes it able to seamlessly and speedily integrate with a wide variaty of databases. This also the foundation that Pandas is built on, a high-performance data-centric package.

In [2]:
import numpy as np
import math

#Array Creation
They are displayed as a list or list of lists and can be created through list as well. When creating an arrray, we pass in a list as an argument in numpy array.

In [ ]:
a = np.array([1,2,3])
print(f'One-dimension A-array: {a}')
print(f'Dimensions of A-array: {a.ndim}')  # this attribute returns the number of dimensions of a list
print(f'Type of items in A-array: {a.dtype}') # it returns the datatype of the items in the array

One-dimension A-array: [1 2 3]
Dimensions of A-array: 1
Type of items in A-array: int64


In [ ]:
b = np.array([[4,5,6], [7,8,9]])
print(f'Two-dimension B-array: \n{b}')
print(f'Length of each dimension of B-array: {b.shape}') # it shows the length of each dimension in a array

Two-dimension B-array: 
[[4 5 6]
 [7 8 9]]
Length of each dimension of B-array: (2, 3)


In [ ]:
c = np.array([1,2.3,3.4]) # an array can be made up of more than integers.
print(c)
print(c.dtype.name)

[1.  2.3 3.4]
float64


We can note that numpy will automatically convert intengers up to floats, since there is no loss of precision. Numpy will try and give the best data type format possible to keep your data type homogeneous, which means all the same, in the array.

# Zeros, Ones and Random
Sometimes we know the shape of the array we want to create but not what we want to be in it. Numpy offers several functions to create arrays with initial placeholders, such as zeros or ones.

In [ ]:
d = np.zeros((2,3)) # It takes a tuple with the dimensions of the array as argument
print(f'Array of zeros:\n{d}')
e = np.ones((2,3))
print(f'Array of ones:\n{e}')
f = np.random.rand(2,3) # It creates a array with placeholders between 0 and 1 in the given shape
print(f'Array of random numbers:\n{f}')

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
[[1. 1. 1.]
 [1. 1. 1.]]
Array of random numbers:
[[0.12422123 0.27564353 0.11886362]
 [0.14927248 0.5423702  0.85776381]]


# Sequences
It's also possible to create a sequence of numbers within a range, with the arange() function. The first argument is the starting bound and the second argument is the ending bound, and the third argument is the difference between each consecutive number, just like the range() function.

In [ ]:
f = np.arange(2,10+1,2)
print(f)

array([ 2,  4,  6,  8, 10])

Now, to create a sequence of floats, we use the linspace() function. In this function, the third argument isn't the difference between two numbers, but the total numbers of itens you want to generate. The first and second arguments are inclusive.

In [ ]:
g = np.linspace(1,2,5)
print(g)

[1.   1.25 1.5  1.75 2.  ]


#Array Manipulation
We can do many things on arrays, such as mathematical manipulation (addition, subtraction, square, exponents) as well as boolean arrays, which are binary values. We can alsodo matrix manipulation such as product, transpose, inverse and so forth.

In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
c = a - b
print(c)
d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


Converting Farenheint temperatures to Celcius.



In [ ]:
farenheit = np.array([0, -10, -5, -15, 0])
celcius = (farenheit - 31) * (5/9)
print(celcius)

[-17.22222222 -22.77777778 -20.         -25.55555556 -17.22222222]


In [ ]:
celcius > -20  # It will return a boolean array for any element in the original

array([ True, False, False, False,  True])

In [ ]:
celcius % 2 == 0  # Another test to check if there are even values in the original array

array([False, False,  True, False, False])

# Matrix Operation
Numpy also supports matrix manipulation.

In [ ]:
# Here is an example of matrix product.
a = np.array([[0,1], [1,2]])
b = np.array([[2,4], [2,2]])

print('ELEMENTWISE PRODUCT') # If we want to do elementwise product, we use the '*' sign.
print(a*b)

print('MATRIX PRODUCT') # If we want to do matrix product, we use the '@' sign or the dot function.
print(a@b)

ELEMENTWISE PRODUCT
[[0 4]
 [2 4]]
MATRIX PRODUCT
[[2 2]
 [6 8]]


In [ ]:
# Remembering that the product of two matrices is only plausible when the inner dimensions of the two matrices are the same.
print(f'Shape of the matrix: A({a.shape}, B({b.shape}))')

Shape of the matrix: A((2, 2), B((2, 2)))


# Useful functions

In [3]:
z = np.array([4, 7, 14, 21, 91])
print(z)
print(f'Z-array sum: {z.sum()}')
print(f'Z-array max: {z.max()}')
print(f'Z-array min: {z.min()}')
print(f'Z-array mean: {z.mean()}')

[ 4  7 14 21 91]
Z-array sum: 137
Z-array max: 91
Z-array min: 4
Z-array mean: 27.4


In [ ]:
# We can also do the same thing to each row or column of an array.
x = np.arange(2,30+1,2).reshape(3,5)
print(x)

# Images

Arrays can be seen as giant ordered lists of numbers, and the shape of an array as just an abstraction that we have for a particular purpose. This is exactly how basic images are stored in computer enviroment.

In [ ]:
from PIL import Image  # Python imaging library
from IPython.display import display  # A function to display images in the Jupyter notebook

# Now, let's open an image
img = Image.open("img/re;.jpeg")
display(img)