<a href="https://colab.research.google.com/github/brunofbpaula/DataScience-UM-Coursera/blob/main/Numpy/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
It's the fundamental package for numeric computing with Python. It provides powerful ways to create, store, and/or manipulate data, which makes it able to seamlessly and speedily integrate with a wide variaty of databases. This also the foundation that Pandas is built on, a high-performance data-centric package.

In [2]:
import numpy as np
import math

#Array Creation
They are displayed as a list or list of lists and can be created through list as well. When creating an arrray, we pass in a list as an argument in numpy array.

In [19]:
a = np.array([1,2,3])
print(f'One-dimension A-array: {a}')
print(f'Dimensions of A-array: {a.ndim}')  # this attribute returns the number of dimensions of a list
print(f'Type of items in A-array: {a.dtype}') # it returns the datatype of the items in the array

One-dimension A-array: [1 2 3]
Dimensions of A-array: 1
Type of items in A-array: int64


In [14]:
b = np.array([[4,5,6], [7,8,9]])
print(f'Two-dimension B-array: \n{b}')
print(f'Length of each dimension of B-array: {b.shape}') # it shows the length of each dimension in a array

Two-dimension B-array: 
[[4 5 6]
 [7 8 9]]
Length of each dimension of B-array: (2, 3)


In [22]:
c = np.array([1,2.3,3.4]) # an array can be made up of more than integers.
print(c)
print(c.dtype.name)

[1.  2.3 3.4]
float64


We can note that numpy will automatically convert intengers up to floats, since there is no loss of precision. Numpy will try and give the best data type format possible to keep your data type homogeneous, which means all the same, in the array.

# Zeros, Ones and Random
Sometimes we know the shape of the array we want to create but not what we want to be in it. Numpy offers several functions to create arrays with initial placeholders, such as zeros or ones.

In [27]:
d = np.zeros((2,3)) # It takes a tuple with the dimensions of the array as argument
print(f'Array of zeros:\n{d}')
e = np.ones((2,3))
print(f'Array of ones:\n{e}')
f = np.random.rand(2,3) # It creates a array with placeholders between 0 and 1 in the given shape
print(f'Array of random numbers:\n{f}')

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
[[1. 1. 1.]
 [1. 1. 1.]]
Array of random numbers:
[[0.12422123 0.27564353 0.11886362]
 [0.14927248 0.5423702  0.85776381]]


# Sequences
It's also possible to create a sequence of numbers within a range, with the arange() function. The first argument is the starting bound and the second argument is the ending bound, and the third argument is the difference between each consecutive number, just like the range() function.

In [29]:
f = np.arange(2,10+1,2)
print(f)

array([ 2,  4,  6,  8, 10])

Now, to create a sequence of floats, we use the linspace() function. In this function, the third argument isn't the difference between two numbers, but the total numbers of itens you want to generate. The first and second arguments are inclusive.

In [30]:
g = np.linspace(1,2,5)
print(g)

[1.   1.25 1.5  1.75 2.  ]


#Array Manipulation
We can do many things on arrays, such as mathematical manipulation (addition, subtraction, square, exponents) as well as boolean arrays, which are binary values. We can alsodo matrix manipulation such as product, transpose, inverse and so forth.